### ISSUE TITLE
Trocando ideias

### ISSUE THREAD

**Issue by NewtonMan** [nfephp-org/sped-emissor#18]
@robmachado esse projeto é realmente muito interessante e acredito que com isso tudo maduro facilitaria demais o uso e implementação em projetos diversos.

Bom eu sou adepto do CakePHP como Framework mas estou interessado em Laravel pois é um outro Framework bastante usado, mas sem problemas já estou trabalhando em algumas coisas para entender como ele funciona.

Como você colocou o projeto em 2 fases eu quero falar a respeito da primeira.

Por experiência, entendo que o trabalho no desenvolvimento precisa ter 3 frentes que, se possível, devem ser módulos distintos.
1 - Criação e/ou Preenchimento do XML
2 - Ações com a SEFAZ
3 - Impressão DANFE

Assim cada módulo estabelece suas convenções de trabalho implementando um comportamento, desse modo o re-uso do projeto todo ou parte dele será simples.

A frente 1 acredito ser um trabalho livre, seguindo aquilo que for melhor e mais fácil para criar e documentar, minha sugestão para essa etapa é que as tabelas e colunas da base de dados respeitem a mesma nomenclatura dada pela SEFAZ, inclusive isso facilita pois o SCHEMA da base serve de orientação para quem vai desenvolver, e a simples leitura/escrita deste documento pode ser importada para a base com os mesmos nomes e etc.

A frente 2 deve estabelecer algumas convenções de operação, eu acho que aqui é o momento de olhar para trás e verificar como podemos voltar a ter aquela estrutura de pastas para operar em cima dela, a ideia é que o módulo tenha uma pasta de input de documentos para cada ação a ser realizada, exemplo: 
sefaz/producao/emitir/
sefaz/producao/lote/enviadas/
sefaz/producao/lote/recebidas/
sefaz/producao/protocolos/
sefaz/producao/cancelar/
sefaz/producao/repositorio/

Através dessa estrutura a frente 2 colocaria robôs para ler NF-es na pasta emitir e transmitiria em lote estas NF-es que em caso de autorização/cancelamento colocaria na pasta repositorio o arquivo ou protocolaria seu cancelamento, lotes enviados e aguardando processamento em lotes/enviadas e lotes processados em lote/recebidas até que conclua as tarefas relacionadas.

Pela frente 3 implementar a impressão em massa, criando também uma pasta com PDFs.

Veja que trabalhando desta maneira seria possível acoplar no futuro o sped-restfull que estaria lidando com dados da frente 2 basicamente pois o XML será recebido externamente.

O que acham?

**Comment by robmachado** [comment]
Na primeira fase estou interessado muito mais no frontend e em deixar um emissor funcional !!
Depois veremos ! uma coisa de cada vez senão não se terminada nada !!
Quanto aos processos serão feitos de forma isolada e poderão ser reaproveitados !

**Comment by NewtonMan** [comment]
Já tem schema da base? Ou posso começar um?

**Comment by robmachado** [comment]
No projeto já tem algumas migrations e views
Mas qq coisa que quiser fazer ANTES abra uma ISSUE e descreva o que vai fazer. Pois não tenho certeza que você entendeu o que escrevi no REAME
