### ISSUE TITLE
projeto morreu

### ISSUE THREAD

**Issue by phsilvasantos** [nfephp-org/sped-emissor#32]
bom dia o projeto morreu?

**Comment by eodantas** [comment]
bom dia, está parado, esperando colaboradores.

Em qua., 3 de jun. de 2020 às 00:46, Paulo Henrique Silva Santos <
notifications@github.com> escreveu:

**Comment by phsilvasantos** [comment]
opa posso ajudar se quiserem tenho app rodando nfe e nfce privado meu com a lib
